name: Go

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PAPERSWITHCODE_API_TOKEN: ${{ secrets.PAPERSWITHCODE_API_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: go build -v ./...
      - run: go test -v ./...

      - uses: go-semantic-release/action@v1.12.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
